name: test project
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: Install NodeJS
              uses: actions/setup-node@v6  
            - name: Install dependency
              run: npm install --package-lock-only
            - name: Run tests
              run: npm test

