name: Deploy project
on: [push,workflow_dispatch]
jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
        - name: get the code
          uses: actions/checkout@v5
        - name: install node
          uses: actions/setup-node@v6
          with:
            node-version: 24
        - name: install dependency
          run: npm ci
        - name: run test
          run: npm test

  build:
    needs: test #wait until job test is successed
    runs-on: ubuntu-latest
    steps:
        - name: get the code
          uses: actions/checkout@v5
        - name: install node
          uses: actions/setup-node@v6
          with:
            node-version: 24
        - name: install dependency
          run: npm ci
        - name: Build project
          run: npm run build
        - name: upload artifacts
          uses: actions/upload-artifact@v4
          with: 
            name: dist-files #give the name of artifect
            path: dist #which files/folders to save as artifacts
  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
        - name: get build artifacts
          uses: actions/download-artifact@v5
          with:
            name: dist-files
        - name: Deploy
          run: echo "deploying..."

          


